#ifndef opencv_win_h
#define opencv_win_h

#ifdef _DEBUG

#if defined(_WIN32)
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_calib3d249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_contrib249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_core249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_features2d249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_flann249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_gpu249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_highgui249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_imgproc249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_legacy249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_ml249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_nonfree249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_objdetect249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_ocl249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_photo249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_stitching249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_superres249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_ts249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_video249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_videostab249d.lib")
#elif defined(_WIN64)
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_calib3d249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_contrib249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_core249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_features2d249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_flann249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_gpu249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_highgui249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_imgproc249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_legacy249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_ml249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_nonfree249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_objdetect249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_ocl249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_photo249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_stitching249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_superres249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_ts249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_video249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_videostab249d.lib")
#endif//defined(_WIN32)

#else

#if defined(_WIN32)
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_calib3d249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_contrib249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_core249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_features2d249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_flann249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_gpu249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_highgui249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_imgproc249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_legacy249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_ml249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_nonfree249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_objdetect249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_ocl249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_photo249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_stitching249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_superres249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_ts249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_video249.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\opencv_videostab249.lib")
#elif defined(_WIN64)

#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_calib3d249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_contrib249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_core249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_features2d249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_flann249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_gpu249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_highgui249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_imgproc249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_legacy249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_ml249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_nonfree249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_objdetect249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_ocl249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_photo249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_stitching249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_superres249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_ts249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_video249d.lib")
#pragma comment(lib, "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\lib\\amd64\\opencv_videostab249d.lib")
#endif//defined(_WIN32)

#endif//_DEBUG

#endif //opencv_win_h